---
- name: Update apt
  sudo: yes
  apt:
    update_cache: yes

- name: Install needed packages
  sudo: yes 
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - reprepro
    - createrepo
