---

- name: ensure /etc/conf.d/ dir exists
  sudo: true
  file: path=/etc/conf.d state=directory

- name: install the systemd configuration file for celery
  template: src=systemd/chacra.sysconfig.j2 dest=/etc/conf.d/chacra-sysconfig
  sudo: true

- name: install the systemd unit file for chacra
  template: src=systemd/chacra.service.j2 dest=/etc/systemd/system/chacra.service
  sudo: true
  notify:
     - reload systemd

- name: install the systemd unit file for celery
  template: src=systemd/chacra-celery.service.j2 dest=/etc/systemd/system/chacra-celery.service
  sudo: true
  notify:
     - reload systemd
