---

- name: Install Statsd Dependencies for Debian
  apt: "name={{ item }} update_cache=yes"
  sudo: true
  # nodejs-legacy is required in Xenial so that it provides the `node`
  # executable
  with_items:
    - git
    - nodejs-legacy
  when: ansible_pkg_mgr == 'apt'

- name: Create node user
  sudo: true
  user: name=node state=present shell=/bin/false system=yes

- name: Install statsd from GitHub
  git: "repo=https://github.com/etsy/statsd.git dest={{ app_home }}/src/statsd update=no version={{ statsd_version }}"

- name: Get directory permissions
  stat: path={{ app_home }}/src/statsd
  register: permissions

- name: Set file permissions
  sudo: true
  file: path={{ app_home }}/src/statsd owner=node group=node
  when: permissions.stat.pw_name != 'node'

- include: systemd.yml

- name: Configure statsd
  sudo: true
  template: src=config/localConfig.js.j2 dest={{ app_home }}/src/statsd/localConfig.js owner=node group=node mode=0444
  notify: restart statsd

- name: Start statsd
  sudo: true
  service: name=statsd state=running enabled=yes
