---

- hosts: test
  user: ubuntu
  roles:
    - celery
    - common
    - repos
    - statsd
  vars:
     app_name: "chacra"
     use_ssl: true
     wsgi_file: wsgi.py
     wsgi_callable: application
     ansible_ssh_port: 2222
     binary_root: "/opt/binaries"
     repos_root: "/opt/repos"
     branch: "master"
     development_server: false
     fqdn: "{{ inventory_hostname }}"
     # required for first deploy
     # api_user: "admin"
     # api_key: "secret"
     # graphite reporting for statsd
     graphite_host: "shaman.ceph.com"
     # required
     # graphite_api_key: '1234-asdf-1234'
     # callbacks
     callback_url: "https://shaman.ceph.com/api/repos/"
     # required for first deploy
     #callback_user: "admin"
     #callback_key: "secret"
     callback_verify_ssl: True
     health_ping: true
     health_ping_url: "https://shaman.ceph.com/api/nodes/"
     use_letsencrypt: True
     nginx_ssl_cert_path: "/etc/letsencrypt/live/{{ fqdn }}/fullchain.pem"
     nginx_ssl_key_path: "/etc/letsencrypt/live/{{ fqdn }}/privkey.pem"
