---

- hosts: all
  user: ubuntu
  roles:
    - celery
    - common
    - repos
    - statsd
  vars:
     app_name: "chacra"
     use_ssl: true
     wsgi_file: wsgi.py
     wsgi_callable: application
     ansible_ssh_port: 2222
     binary_root: "/opt/binaries"
     repos_root: "/opt/repos"
     branch: "master"
     development_server: false
     fqdn: "chacra.ceph.com"

     # graphite reporting for statsd
     graphite_host: "shaman.ceph.com"
     # required
     # graphite_api_key: '1234-asdf-1234'

     # callbacks
     callback_url: "https://shaman.ceph.com/api/repos/"
     # required
     #callback_user: "admin"
     #callback_key: "secret"
     health_ping: true
     health_ping_url: "https://shaman.ceph.com/api/nodes/"
