---

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: restart app
  register: app_restart
  service: name=chacra state=restarted enabled=yes

- name: restart celery
  service: name=chacra-celery state=restarted enabled=yes
  when: app_restart.changed
