---

- name: reload systemd
  sudo: yes
  sudo: yes
  command: systemctl daemon-reload

- name: restart app
  register: app_restart
  sudo: yes
  service: name=chacra state=restarted enabled=yes

- name: restart celery
  service: name=chacra-celery state=restarted enabled=yes
  sudo: yes
  when: app_restart.changed

- name: restart nginx
  sudo: yes
  action: service name=nginx state=restarted
