---

- name: restart app
  command: "{{ app_home }}/bin/circusctl restart {{ app_name }}"
  register: app_restart

- name: restart celery
  command: "{{ app_home }}/bin/circusctl restart celery"
  register: celery_worker
  when: app_restart.changed

- name: "restart celery worker 2"
  command: "{{ app_home }}/bin/circusctl restart celery-worker2"
  register: celery_worker_2
  when: celery_worker.changed

- name: "restart celery worker 3"
  command: "{{ app_home }}/bin/circusctl restart celery-worker3"
  register: celery_worker_3
  when: celery_worker_2.changed

- name: "restart celery worker 4"
  command: "{{ app_home }}/bin/circusctl restart celery-worker4"
  register: celery_worker_4
  when: celery_worker_3.changed

- name: restart celery beat
  command: "{{ app_home }}/bin/circusctl restart celerybeat"
  when: celery_worker_4.changed

- name: restart nginx
  sudo: yes
  action: service name=nginx state=restarted

- name: reload circusd
  sudo: yes
  action: service name=circus state=reloaded

- name: reload circus config
  command: "{{ app_home }}/bin/circusctl reloadconfig"

- name: start circus
  sudo: yes
  action: service name=circus state=started

- name: restart circus
  sudo: yes
  action: service name=circus state=restarted
