---

- name: reload systemd
  sudo: yes
  sudo: yes
  command: systemctl daemon-reload

- name: restart app
  sudo: yes
  service: name=chacra state=restarted enabled=yes

- name: restart chacra-celery
  service: name=chacra-celery state=restarted enabled=yes
  sudo: yes

- name: restart chacra-celerybeat
  service: name=chacra-celerybeat state=restarted enabled=yes
  sudo: yes

- name: restart nginx
  sudo: yes
  action: service name=nginx state=restarted
