---

- name: reload systemd
  become: true
  become: true
  command: systemctl daemon-reload

- name: restart app
  become: true
  service: name=chacra state=restarted enabled=yes

- name: restart chacra-celery
  service: name=chacra-celery state=restarted enabled=yes
  become: true

- name: restart chacra-celerybeat
  service: name=chacra-celerybeat state=restarted enabled=yes
  become: true

- name: restart nginx
  become: true
  action: service name=nginx state=restarted
