---

- hosts: all
  user: ubuntu
  roles:
    - celery
    - common
    - repos
    - statsd
  vars:
     app_name: "chacra"
     use_ssl: true
     wsgi_file: wsgi.py
     wsgi_callable: application
     ansible_ssh_port: 2222
     binary_root: "/opt/binaries"
     repos_root: "/opt/repos"
     branch: "master"
     development_server: false
     fqdn: "chacra.ceph.com"

     # graphite reporting for statsd
     graphite_host: "shaman.ceph.com"
     # this *must* be passed in as an extra-vars option if wanting
     # to report to the production graphite instance
     # graphite_api_key: '1234-asdf-1234'
