---

- hosts: all
  user: vagrant
  roles:
    - celery
    - common
    - repos
    - statsd
  vars:
     app_name: "chacra"
     use_ssl: true
     wsgi_file: wsgi.py
     wsgi_callable: application
     ansible_ssh_port: 22
     restart_app: true
     binary_root: "/opt/binaries"
     repos_root: "/opt/repos"
     branch: "master"
     development_server: true
     fqdn: "localhost"

     # callbacks
     callback_url: ""
     callback_user: "admin"
     callback_key: "secret"
